### ISSUE TITLE
ActionView::Template::Error (couldn't find file 'semantic_ui/definitions/modules/accordion.less' with type 'text/css'):

### ISSUE THREAD

**Issue by bilalmaqsood** [Semantic-Org/Semantic-UI-Rails-LESS#12] opened 2015-07-08 08:53 UTC
I followed all the instructions in the read me file, but still unable to get up and running with usage of Semantic UI.

**Comment by maxd** [comment] 2015-07-08 09:15
Could you please provide minimal project for reproduce problem?

**Comment by bilalmaqsood** [comment] 2015-07-08 10:26
It is actually the minimal project. I'm using Rails 4.2.1, ruby 2.1.2. Create a new project `rails new <project_name>`. First thing: I installed the gems that you asked, and ran the commands as described in read me file, and got this. Need more info, please let me know, I'd be glad to explain.

**Comment by maxd** [comment] 2015-07-08 12:03
Checked. All works fine. Still need minimal project for reproduce your problem.

**Comment by postbud** [comment] 2015-07-14 10:16
A similar problem in the process of running the application.
It was decided by manually adding gem 'less-rails'

**Comment by maxd** [comment] 2015-07-21 11:07
I close it. Without minimal project is impossible to reproduce problem.

**Closed by maxd** 2015-07-21 11:07 UTC

**Comment by btreeinfinity** [comment] 2015-11-21 02:31
I'm having this issue, latest rails 4.2.5, new project, only your instructions.

**Comment by gustavosantiago** [comment] 2015-12-18 07:59
i don't know how to execute this gem because everything i use the comands, rails give me a same error
"couldn't find file 'semantic_ui/definitions/modules/accordion.less' with type 'text/css'"
can you help me?

ps: i have, less-rails gem

**Comment by postbud** [comment] 2015-12-18 08:36
And if to create the empty file accordion.less?

**Comment by gustavosantiago** [comment] 2015-12-18 14:50
i follow step-by-step the instructions for install the gem in my project, when i execute rails s and refresh a page, rails give me this error.

**Comment by maxd** [comment] 2015-12-18 15:22
Create minimal project for reproduce problem and I will try to investigate reason of it.

**Comment by postbud** [comment] 2015-12-19 01:49
**gustavosantiago**, my apologies. The idea to create an empty file was not from here.I messed up projects.
But I decided to double-check the installation:

use rvm
1. install ruby 2.2.4p320
2. create rvm gemset
3. install rails  4.2.5
4. create new project `rails new app`
5. add to Gemfile
   `gem 'less-rails-semantic_ui'`
   `gem 'less-rails'`
    
run `bundle install`, `rails s`
and I received an error:

_/gems/less-rails-2.7.0/lib/less/rails/railtie.rb:19:in `block in <class:Railtie>': undefined method `register_preprocessor' for nil:NilClass (NoMethodError)_

as it is clear at the moment, the problem is 'sprockets-rails'. search for a problem I did not.

my solution: 
    add `gem 'sprockets-rails', '<=2.3.3'`  (a string of project works)

run `bundle update`, `rails s`

successful start

after:
6. run `rails generate semantic_ui:install`
7. add lines  in application.js and .css
   `//= require semantic_ui/semantic_ui`
   `*= require semantic_ui/semantic_ui`
8. create view with semantic-ui class
9. start rails	

successful start

***file listing***
<details> 
  <summary>Gemfile</summary>
 ```
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
 gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
#  gem 'spring'
end
gem 'less-rails-semantic_ui'
gem 'less-rails'
gem 'sprockets-rails', '<=2.3.3'

```
</details>
<details> 
  <summary>Gemfile.lock</summary>
```
GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.2.5)
      actionpack (= 4.2.5)
      actionview (= 4.2.5)
      activejob (= 4.2.5)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.5)
      actionview (= 4.2.5)
      activesupport (= 4.2.5)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (4.2.5)
      activesupport (= 4.2.5)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    activejob (4.2.5)
      activesupport (= 4.2.5)
      globalid (>= 0.3.0)
    activemodel (4.2.5)
      activesupport (= 4.2.5)
      builder (~> 3.1)
    activerecord (4.2.5)
      activemodel (= 4.2.5)
      activesupport (= 4.2.5)
      arel (~> 6.0)
    activesupport (4.2.5)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    arel (6.0.3)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    builder (3.2.2)
    byebug (8.2.1)
    coffee-rails (4.1.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.1.x)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    commonjs (0.2.7)
    concurrent-ruby (1.0.0)
    debug_inspector (0.0.2)
    erubis (2.7.0)
    execjs (2.6.0)
    globalid (0.3.6)
      activesupport (>= 4.1.0)
    i18n (0.7.0)
    jbuilder (2.3.2)
      activesupport (>= 3.0.0, < 5)
      multi_json (~> 1.2)
    jquery-rails (4.0.5)
      rails-dom-testing (~> 1.0)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    json (1.8.3)
    less (2.6.0)
      commonjs (~> 0.2.7)
    less-rails (2.7.0)
      actionpack (>= 4.0)
      less (~> 2.6.0)
      sprockets (> 2, < 4)
      tilt
    less-rails-semantic_ui (2.1.6.0)
      less-rails (>= 2.6.0, <= 2.7.0)
    libv8 (3.16.14.13)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    mime-types (2.99)
    mini_portile2 (2.0.0)
    minitest (5.8.3)
    multi_json (1.11.2)
    nokogiri (1.6.7.1)
      mini_portile2 (~> 2.0.0.rc2)
    rack (1.6.4)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.5)
      actionmailer (= 4.2.5)
      actionpack (= 4.2.5)
      actionview (= 4.2.5)
      activejob (= 4.2.5)
      activemodel (= 4.2.5)
      activerecord (= 4.2.5)
      activesupport (= 4.2.5)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.5)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.7)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.2)
      loofah (~> 2.0)
    railties (4.2.5)
      actionpack (= 4.2.5)
      activesupport (= 4.2.5)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.4.2)
    rdoc (4.2.0)
    ref (2.0.0)
    sass (3.4.20)
    sass-rails (5.0.4)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    sprockets (3.5.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (2.3.3)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    sqlite3 (1.3.11)
    therubyracer (0.12.2)
      libv8 (~> 3.16.14.0)
      ref
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (2.0.1)
    turbolinks (2.5.3)
      coffee-rails
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    web-console (2.2.1)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)

PLATFORMS
  ruby

DEPENDENCIES
  byebug
  coffee-rails (~> 4.1.0)
  jbuilder (~> 2.0)
  jquery-rails
  less-rails
  less-rails-semantic_ui
  rails (= 4.2.5)
  sass-rails (~> 5.0)
  sdoc (~> 0.4.0)
  sprockets-rails (<= 2.3.3)
  sqlite3
  therubyracer
  turbolinks
  uglifier (>= 1.3.0)
  web-console (~> 2.0)

BUNDLED WITH
   1.11.2

```
</details>

**Comment by gustavosantiago** [comment] 2015-12-19 02:41
i don't have success with this, i don't see where i wrong


My gemfile

source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.4'
# Use postgresql as the database for Active Record
gem 'pg', '0.18.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
# gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Flexible authentication solution for Rails
#gem 'devise'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', '~> 0.4.0'
end

# Compile less files
gem 'less-rails'
# Provides the ability to customize component themes and variables with Semantic Ui
gem 'less-rails-semantic_ui', '~> 2.1.6.0'
# Use for improve compatibility with different browsers
gem 'autoprefixer-rails'
gem 'sprockets-rails', '<=2.3.3'

group :development do
  # Inspect source code live through a console that works on every stack frame
  gem 'better_errors'
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  # View missing link between the browser and your app code
  gem 'xray-rails'
end

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  # Generate model and controller UML class diagram
  gem 'railroady', '~> 1.0.9'
end

**Comment by postbud** [comment] 2015-12-19 07:35
***gustavosantiago*** I use your  Gemfile.
Add only `gem 'sqlite3'`.
Everything is working

**Comment by maxd** [comment] 2015-12-19 09:02
@gustavosantiago Disable or restart [spring](https://github.com/rails/spring). Then try to reproduce problem again.

**Comment by gustavosantiago** [comment] 2015-12-20 02:17
Guys, i got it, I enable the unicorn gem (thats crazy) and works.
@postbud, I see in your gemfile a unicorn uncommented, so a reply this
Thanks very much @maxd and @postbud, i will prepare a tutorial for my friends on Brazil for don't passing through it again.
